# To Do 

fix output location of knits for files in /04-text

+ make a subfolder (output)

draw diagram that outlines workflow of this project...draw data in then munge then write to table to..., then import data from to .rmd...bla bla 

Remove typos!
Use the devtools::spell_check() function. Typos in documentation are not the end of the world but can annoy the user, and it’s not hard to remove them thanks to this tool, so do it when you get a chance.

lots of advice to follow here

https://holtzy.github.io/Pimp-my-rmd/

https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html 


## Data



## Write up
explain and list the test that were conducted.
explain which part are taken further into considerring for analasys and why.

Im not too happy with the layout structure and flow. compare with professional technical report in the industry.


## Tables, Plot, Figs, Formulas

### Plot
simple small plots off all raw distributions.

this same plot can be plot next to the OS and US streams.

Then do the same for the modelled streams.

### Formulas


+ double check RR Latex formula in (d/l?)


 $$F\left(d\right) = exp\left[-(\frac{d}{l})^{m} \right]$$


+ add regression formulas that include the coeficients

+ result, discussion section?

### Tables

+ add row in distribution figures 
+ wrap text in col names of R2
tableshttps://community.rstudio.com/t/wrap-column-name-in-pdf-table-from-knitr-kable/3278/4
+also add latex formulas

+ repair layout of model coef tables in "Results and Discussion sectio:

+ fix rounding 
+ fix layout



The RR transformation is achieved by taking the natural log twice and simplified as:
#$$\ln\left\{-\ln\left[1-F(d)\right] \right\} = m\times \ln d - m\times \ln \bar{d} $$


