---
output:
  pdf_document: default
  html_document: default
---

```{r, include = FALSE}
#Function here::here to help with file paths relative to the project folder:
library("here")

#attache rpackages from central location:
source(here::here("02_rpackages",'projectpackages.R'))
knitr.table.format = "latex"
```

```{r, include = FALSE }


#This Rmd draws in the model coef data and generates the table for use in the results and discussion section as RMardown 'mother-child' doc relationship.
```


```{r echo = FALSE}
# bring in the saved data to be tabled:
#data was generated by file x???
CoefRR <- read.csv(file = here::here("03_code/01_code-output","CoefRR.csv"))

CoefGGS <- read.csv(file = here::here("03_code/01_code-output","CoefGGS.csv"))

```


```{r echo = FALSE, results='asis'}


tblCoefRR <- knitr::kable(CoefRR,
                        "latex",
                        escape = F,booktabs = T, 
                        digits = c(0,0,3)) %>% 
  column_spec(1, width = "3cm") %>% 
  column_spec(2:3, width = "1.5cm") %>% 
  kable_styling(c("striped", "bordered"))
  #this column_spec is supposed to set column widths to force text to wrap inside the colmn #https://community.rstudio.com/t/wrap-column-name-in-pdf-table-from-knitr-kable/3278/4)
                        #caption="RR Model(formula)") # %>%
#  kable_styling(c("striped", "bordered"), 
                #full_width = F) %>% 
#https://www.rdocumentation.org/packages/kableExtra/versions/1.1.0/topics/column_spec



tblCoefGGS <- knitr::kable(CoefGGS,
                  "latex",
                  escape = F, booktabs = T, 
                  digits = c(0,0,3)) %>% 
  column_spec(1, width = "3cm") %>% 
  column_spec(2:3, width = "1.5cm") %>% 
  kable_styling(c("striped", "bordered"))




#code below posistions tables side by side

cat(c("\\begin{table}[!htb]
    \\begin{minipage}{.5\\linewidth}
      \\caption{RR Model Coeficients}
      \\centering",
        tblCoefRR,
    "\\end{minipage}%
    \\begin{minipage}{.5\\linewidth}
      \\centering
        \\caption{GGS Model Coeficients}",
        tblCoefGGS,
    "\\end{minipage}
\\end{table}"
))


```