## Model fitting

Modeling of particle size distributions are statical procedures where distributions with known distribution functions are used to compare or model real life distribution to.

The two most commmonly used distributions in Geology and Mineral Processing and specifically comminution circuits are the Roslin-Rammler and the Gates-Gaudin-Schumann distributions.

Both models were used  to model all PSD screening data to, and the subsequent best fit model was selected in each case. Model selection was determined by comparing each PSD's transformed linear model's determinant ($R^2$).
Interpolation betweeen measured sizing points is conducted by the back-transformation of the model-fitted points along the respective model's distribution function. 



### Rosin Rammler (RR) Model:
The RR model distribution function has been used to describe the particle size distributions of various minerals, powders and liquids of various types and sizes. The function is particularly suited to represent those produced by grinding, milling, and crushing operations. The general expression of the RR model is:

\begin{equation}

  F\left(d\right) = exp\left[-(\frac{d}{l})^{m} \right]

  \label{eq : RR}
\end{equation}




where:  
$F(d)$ = distribution function (cum. passing)  
$d$ = particle size [mm]  
Parameters $\bar{d}$ and $m$ are adjustable parameters characteristic of the distribution.   
$\bar{d}$ = scale paramater (mean particle size [mm]) and  = $\exp\left({-\frac{intercept}{slope}}\right)$.    
$m$ = slope paramater (measure of the spread of particle sizes).  



The RR transformation is achieved by taking the natural log twice and simplified as:
$$\ln\left\{-\ln\left[1-F(d)\right] \right\} = m\times \ln d - m\times \ln \bar{d} $$
Note that the RR distribution transformation is conducted on the cummulative retained distribution (thus the $\left[1-F(d)\right]$.)

If a distribution plots a straight line after the above RR transformation, then the distrubution can be represented by the RR distribution function. This will alllow percentile interpolation according to the distribution and not a straight line between two points obatained from screening. 


$$ Y=mX + C$$


$$\underbrace{\ln\left\{-\ln\left[1-F(d)\right] \right\}}_\textrm{Y} =  \underbrace{m}_\textrm{slope}\times \underbrace{\ln d}_\textrm{X}+\underbrace{ \left(-m\times \ln \bar{d}\right)}_\textrm{C} $$

#### Back-transformation
(This is really the reason why we're doing the model fitting; so that we can better estimate the size at which a certain specified mass fraction will pass). 
The back-transform is then conducted to determine the required percentile values:

$$ x = \bar{d} \left(- \ln \left(1-Y \right)    \right)^\frac{1}{m}$$
$$size = scale parameter\times (-\ln (1-percentile))^{1/slope parameter}$$ ,
where the scale_parameter; is a function of the slope and intercept of the transf
ormed RR model fit, as follows: $$scale parameter = exp(-\frac{intercept}{slope} )$$




### Gates-Gaudin-Schumann (GGS) Model:

The Gates-Gaudin-Schumann plot is a graph of **cumulative % passing versus nominal
sieve size**, with both the $X$ and $Y$ axes being logarithmic plots. In this type of plot, most of the data points (except for the two or three coarsest sizes measured) should lie nearly in a straight line.

$$y = F(x) = \left(\frac{x}{k}\right) ^n$$
or simmilarly:
The above formula can be rewritten as:
$x = k \times y ^ \frac{1}{n}$  


where:  
$y$ = $F \left(x\right)$ = cumulative undersize distribution function.  
$x$ = particle size,  
$k$ = maximum particle size of the transformed straight line corresponding to $100%$ cum. passing.


Log transformation of the distribution yields:

$$\ln y = n \ln x - n \ln k$$

Applying this transformation to the measured observed distribution data points will yield near straight lines if the data fits the model.




If the size distribution of particles from a crushing or grinding operation does not
approximate a straight line, it suggests that there may have been a problem with the data
collection, or there is something unusual happening in the comminution process.
The size modulus is a measure of how coarse the size distribution is, and the distribution
modulus is a measure of how broad the size distribution is. Size modulus for a size
distribution can be determined from a graph by extrapolating the straight-line portion up
to 100% passing and finding the corresponding size value. The distribution modulus can
be calculated by choosing two points in the linear portion of the graph, calculating the
logs of the sizes and % passing values, and calculating the slope. 








RR model fits the feed streams means (F13m and F14m) better (near straight line QQ fits) than the Oversize streams.
