# To Do 


lots of advice to follow here

https://holtzy.github.io/Pimp-my-rmd/

https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html 


## Data



## Write up

Im not too happy with the layout structure and flow. compare with professional technical report in the industry.


## Tables, Plot, Figs, Formulas

### Plot

move plot (unmodelled psd) out of "sampling" section; should be in results.
this same plot can be plot next to the OS and US streams.
Then do the same for the modelled streams.

### Formulas

Modelfurmulas section does render to PDF. error with inline `R` code.
+ double check RR Latex formula in (d/l?)


\begin{equation}

  F\left(d\right) = exp\left[-(\frac{d}{l})^{m} \right]

  \label{eq : RR}
\end{equation}


+ add regression formulas that include the coeficients

++ result, discussion section?

### Tables

+ wrap text in col names of R2
tableshttps://community.rstudio.com/t/wrap-column-name-in-pdf-table-from-knitr-kable/3278/4
+also add latex formulas

+ repair layout of model coef tables in "Results and Discussion sectio:

++ fix rounding 
++ fix layout



The RR transformation is achieved by taking the natural log twice and simplified as:
$$\ln\left\{-\ln\left[1-F(d)\right] \right\} = m\times \ln d - m\times \ln \bar{d} $$


